# Generated by Django 5.2.7 on 2025-10-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_stock_quantity_alter_stock_ticker_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='linked_stock',
            field=models.ForeignKey(blank=True, help_text='Optionally link this goal to a specific stock in your portfolio.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.stock'),
        ),
    ]
