# Generated by Django 5.2.7 on 2025-10-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_goal_linked_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksymbol',
            name='sector',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
