# Generated by Django 5.2.7 on 2026-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_alertthreshold_threshold_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
